export { default as Header } from "./header/header";
export { default as Hero } from "./hero/hero";
export { default as Services } from "./services/services";
export { default as About } from "./about/about";
export { default as Skills } from "./skills/skills";
export { default as Projects } from "./projects/projects";
export { default as CTA } from "./cta/cta";
export { default as Footer } from "./footer/footer";
export { default as SectionTitle } from "./sectionTitle/sectionTitle";