export { default as Header } from "./sections/header/header";
export { default as Hero } from "./sections/hero/hero";
export { default as Services } from "./sections/services/services";
export { default as About } from "./sections/about/about";
export { default as Skills } from "./sections/skills/skills";
export { default as Projects } from "./sections/projects/projects";
export { default as CTA } from "./sections/cta/cta";
export { default as Footer } from "./sections/footer/footer";
export { default as SectionTitle } from "./utils/sectionTitle/sectionTitle";